ExoCTK/exoctk

ExoCTK/pal/_exotransmit_wrapper.pyx, ExoCTK/pal/include/main_transmission.c
This causes a bug where the Python prompt starts when exotransmit is run, presumably do to some naming conflict with "main".
=> change name of main() function in exotransmit C code

ExoCTK/contam_visibility/visibilityPA.py
The use of matplotlib.use('Agg') makes it tedious to use `ExoCTK` in an analysis framework, such as when implementing it inside of `AWESim_SOSS`.  It may be necessary for the `ExoCTKWeb`; but let the web app implemented it.
=> Commented out matplotlib.use('Agg')

setup.py
When trying to import `exoctk` there is a dependency on `asteval` that was not in the `setup.py` file.
=> Added asteval dependency

setup.py
This PR simply switches the `zip_safe` parameter in `setup.py` to `True` to help the ExoMast team more easily install the `exoctk` package.
This pertains to #202
=> Install for ExoMast: Setting zip_safe to True

exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/templates/groups_integrations.html
Added the basic retrieval functionality. Was thinking maybe in the future, we could break up the model drop down for stellar type, teff, and log(g) into separate buttons and then select the upper or lower limit of allowed values for the models based on whats returned from the API call.
=> Added Exomast API retrieval for Groups and Integrations

exoctk/exoctk_app/app_exoctk.py
this fixes a bug in the NIRCam option for the Contam Overlap tool
explanation: 
because NIRCam has 2 form options, the input parameter`form.inst.data` will return `NIRCam F444W` or `NIRCam F322W2`. this breaks the function, because it just wants `NIRCam` without the filter option. so I just split the string and pulled the `NIRCam` portion out of it
=> fixed the nircam option for visibility calc

exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/form_validation.py, exoctk/exoctk_app/templates/index.html, exoctk/groups_integrations/groups_integrations.py
This is a not particularly elegant fix for #282.
It looks like for some reason when you open the Groups and Integrations Calculator, it's trying to form submit right then and there. (I would bet this is true for all/most of the other API wrapped forms) but this one needs to immediately do math operations on the at this time empty inputs, and the attempted type casting of nothing throws an error.
My fix for now is to catch this error, make sure it's a nonetype, and give it a chance to chill and see if some more input gets thrown that way. For the case that (I'm not sure exists but 🤷‍♂ ) I wrote a little custom message and rerouted it to the error template. 
@mfixstsci I would definitely like your input in case this has unforseen complications.
=> Hot fix for groups and integrations.

exoctk/exoctk_app/app_exoctk.py
Had to replace form parsing with `if/else` block for now to make units for the groups and integrations to return correct observation times. If a user is coming from EXOMAST the conversion is done automatically, but if they want it in days, they will have to do it on their own or retrieve it from the url or EXOMAST.
=> Fixing unit bug

exoctk/contam_visibility/visibilityPA.py
This puts in two small fixes for #285 .
It sets a default limit of the visibility plot to (0,360), as well as turns the line plots to sluggy little circle plots to get rid of the plotting over discontinuities.
=> Bokeh contam updates

exoctk/exoctk_app/templates/groups_integrations_results.html
The max and min duration time are flipped. 
NOTE : it may be that they are flipped in the code, not in the template, but I'm switching them for now, and I will dig into the code at a later date.
=> Flipped min and max duration time.

exoctk/contam_visibility/sossFieldSim.py, exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/form_validation.py, exoctk/forward_models/forward_models.py, exoctk/tests/test_atmospheric_retrievals.py, exoctk/utils.py
This PR adds a new function `get_env_variables` that stores and returns the `EXOCTK_DATA` env variable and subsequent dependent env variables (e.g. `MODELGRID_DIR`) in a dictionary.  This function can then be called to retrieve these data when needed, instead of having it all in the global scope of `utils.py`.
Closes #298
=> Remove EXOCTK_DATA from global scope

ci/install_conda.sh, exoctk/lightcurve_fitting/simulations.py, exoctk/tests/test_lightcurve_fitting.py
The install looks for `sphinx` but finds `sphinx-astropy` and installs it twice so there is an `ImportError` when it looks for the former. This adds a manual `sphinx` install when the conda environment is set up.
=> Adding manual sphinx install

exoctk/phase_constraint_overlap/phase_constraint_overlap.py
Tool is supposed to pick the max value between `(6, 3*transitDur+1)` not the minimum.
=> Correction for observation duration for phase overlap

exoctk/contam_visibility/sossContamFig.py, exoctk/contam_visibility/sossFieldSim.py, exoctk/utils.py
Playing around with a fresh installation of ExoCTK, found out that there was no way to use the new `exoctk.utils.download_exoctk_data()`, because when the `EXOCTK_DATA` environment is not set, `os.environ.get('EXOCTK_DATA')` is `None` by default which leads to some crashes. 
This PR fixes this behavior, so a fresh installation of ExoCTK without defining the `EXOCTK_DATA` environment (and thus, without even thinking of downloading the ExoCTK dataset) enables the user to import exoctk without the code crashing. It still warns the user that the environment has to be set several times to have full functionality.
Defining @bourque and @jaymedina to review this as they both worked on the imporvement of the `exoctk/utils.py` code to allow for the data to be downloaded via the …
=> Modified utils plus contam_visibility files so import works 

exoctk/contam_visibility/visibilityPA.py
RA and Dec are handled as strings by some functions, either in hh:mm:ss.s or dd:mm:ss.s format or representing a float. Updating documentation to match.
Found this while updating sanitizing input of MAST exo-mast web services that call this library. Similar updates may need to be made elsewhere in exoctk, but this is as far as I've looked.
=> updating docstrings: RA and Dec as str

env/environment-3.6.yml, env/environment-3.7.yml, exoctk/exoctk_app/app_exoctk.py, exoctk/forward_models/forward_models.py, pip_requirements.txt
This PR updates `bokeh` to version `2.2.3` and solves issues with the use of `bokeh.util.string.encode_utf8`
=> Fix issues with bokeh v2.x

README.rst
This PR adds citation information to the `README` file as part of the Tier 2 Software Standards for INS JWST tools.  Closes #443.
In this process, I created a Zenodo publication for the project, found here: https://zenodo.org/record/4556063/export/hx#.YDQepFlOmCM
Since I was changing `README`, I also took this opportunity to fix/add some badges.
=> Added citation information

env/environment-3.7.yml, env/environment-3.8.yml, env/environment-3.9.yml, exoctk/contam_visibility/field_simulator.py, exoctk/forward_models/forward_models.py, exoctk/log_exoctk.py, exoctk/modelgrid.py, exoctk/utils.py, pip_requirements.txt
Resolves #386 by allowing ExoCTK data to be downloaded as needed for each tool.
=> Data download for individual tools

CHANGELOG.md, README.rst, exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/templates/base.html, setup.py
Hi folks,
Here comes a (hot) fix to a bug found by Nikolay Nikolov, in which the phase-constraint wouldn't work if eccentricity is not set manually to a number (or when not found by the target resolver). The problem was very simple: when the parameter is not found, it is populated by `None` by default in the web app forms. In theory we had solved this over a year ago, but apparently in the code I was double setting `omega` (and not `eccentricity`) as `np.nan` (which the web app form likes more than `None` values). I have now fixed that.
In addition, I took the liberty of updating all the info in the `setup.py`, `CHANGELOG.md` and the web-app to match the next version release with this bug fixed (and Matthew's sweep of PEP8 on the code). I also took the liberty of updating the `Readme.rst` …
=> Phase constraint hotfix + ready for development updates

exoctk/contam_visibility/visibilityPA.py
Fixing date format on hover tool. Removing `TOOLTIPS` and making hover definition explicit. Here is a screen shot when running the webapp locally with the changes.
=> Fixing Date Formatter

exoctk/limb_darkening/__init__.py, exoctk/limb_darkening/spam.py
Hi ExoCTK'ers,
This is a set of limb-darkening addons to the whole package; some are suggestions I received from colleagues working on limb-darkening (which loved the package by the way!), some are some addons I needed for my own science work that I decided would be freebies to add to ExoCTK. The list of addons (and the completion status) is:
I'll suggest a reviewer once I've completed the set of tasks outlined here!
=> [WIP] Various limb-darkening addons

exoctk/exoctk_app/app_exoctk.py
NRS does not have a dictionary key in `field_simulator.APERTURES`. This checks the value being passed from the form and if it is NRS, just make the instrument variable the string passed from the form. Data from the dictionary is only needed for calculating contamination.
=> Fix NRS Visibility Plot

exoctk/exoctk_app/app_exoctk.py
The web application doesn't recognize the default form value for the k band magnitude in the groups and integrations tool. This causes the target resolving portion of the tool to fail unless users add a value in to the form before submission. Hopefully these updates will fix the problem.
=> Groups and Integrations Form Validation Bug
