ExoCTK/exoctk

.travis.yml, ExoCTK/__init__.py, ExoCTK/tests/test_example.py, setup.cfg, setup.py
Travis builds all fail trying to install dependencies.
=> Fix travis

.travis.yml, docs/index.rst
travis needs `mock` to build sphinx
=> Fix travis round 2

ExoCTK/core.py, ExoCTK/helpers.py, ExoCTK/ldc/ldcfit.py, ExoCTK/ldc/ldcplot.py
A few changes to the ModelGrids are handled to speed up LDC calculations:
- Loaded flux arrays are now written to HDF5 files
- Grid can now be reset after customize() method is run
- Nice printing for ldc calculations using multiple profiles
=> Minor rewrite of ldc

ExoCTK/pal/exotransmit.py
This causes problems when running in a python session.
=> remove check from exotransmit

ExoCTK/tor/tor.py
Hello.
Look at me -- another WIP merge request...
Start of TOR tool -- right now I have the logic worked out post groups -- groups to be added in shortly.
=> WIP: Working on the TOR functions.

ExoCTK/ldc/ldcfit.py
=> Fixed input of only one limb darkening profile so it is converted to a list

ExoCTK/pal/setup_package.py
=> fix windows path

ExoCTK/tor/visibilityPA.py
Got the dates to display finally! Converted to day number and THEN to date time seems to work.
=> Fixed date axis labels on target visibility plot.

ExoCTK/tor/sossContamFig.py
=> Getting there

ExoCTK/tor/sossContamFig.py
=> Added title to contam plots.

ExoCTK/tor/tor.py
The real noticeable change was that I fixed a bug wherein the saturation level was getting set wrong for TA mode -- but I also took this as an opportunity to clean house.
=> Fixing the TA saturation error.

ExoCTK/tor/sossContamFig.py
=> Added linked panning and shaded regions to tor2 contam plots.

ExoCTK/limb_darkening/limb_darkening_fit.py
Fixed funcitonal form for logarithmic limb darkening law. See Issue #71 for the rationale. Also, practicing doing a pull request.
=> fix functional form for logarithmic limb darkening law #71

.gitignore, .gitingore
Deleted `.gitingore` and added lines to `.gitignore`.
=> Cleaned up .gitignore stuff.

ExoCTK/notebooks/integrations_groups_demo.ipynb
Notebook achieved. I'd love if someone would run through and test it though. 
Closes #131.
=> A beauitfully crafted demo notebook -- just for the IGC.

exoctk/contam_visibility/resolve.py, exoctk/phase_constraint_overlap/phase_constraint_overlap.py, exoctk/utils.py, setup.py
Currently struggling with reading in the default of the arg parse values. Could hard code it, but that seems less neat.
=> [WIP]: Phase constraint tool

exoctk/exoctk_app/templates/limb_darkening.html
This both makes more sense from a UI standpoint and it somewhat patches the issue of the rest of the form being wiped out when the used clicks Retrieve Parameters.
=> Put stellar params at top of the LDC form.

README.rst
This PR adds installation instructions to the `README.rst` file for users and contributors
=> Install instructions

README.rst, docs/index.rst, exoctk/exoctk_app/templates/base.html
Adds information to our github README, the Read the Docs main page, and the ExoCTK website main page about how to email and add oneself to the newsletter subscription.
=> Newsletter updates

setup.py
This PR makes some changes to `setup.py` per request of the ExoMAST team.
=> ExoMAST patch for setup.py

exoctk/helpers.py, exoctk/lightcurve_fitting/models.py, exoctk/modelgrid.py, exoctk/references.py, exoctk/utils.py, pip_requirements.yml, setup.py
=> Made a few modules PEP compliant and removed batman as a requirement.

README.rst, docs/index.rst
Added more package info, link to readme for installation info
=> Tidying Documentation 

exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/form_validation.py, exoctk/exoctk_app/templates/generic.html, exoctk/utils.py
Just put the Generic Model Grid tool back in. Sorry @julesfowler !
I also made a class for the form validation but didn't implement it. We can do that later if we want.
=> Put generic grid back

exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/form_validation.py, exoctk/modelgrid.py, exoctk/utils.py
This PR adds all of url parameter retrieval work that I did back into the app. I added the functionality to the contamination and visibility and the groups and integrations tools. There are example urls for the local app as comments on lines 408 and 266.
=> Add query params

README.rst
The data download is getting rather tiresome, so I figured it needed to be well documented in our README.
=> Updated readme.

exoctk/exoctk_app/templates/contam_visibility.html, exoctk/exoctk_app/templates/contam_visibility_results.html
modifications to the explanatory text in Contam Overlap tool
=> fixing typos

exoctk/exoctk_app/templates/generic.html
This contains some tweaks to the template to address @kevin218's suggestions in #286.
=> Updating to point to Jayesh's paper and unit fix.

exoctk/contam_visibility/sossContamFig.py, exoctk/contam_visibility/visibilityPA.py, exoctk/exoctk_app/templates/index.html
addressing some of the comments from Issue #285
=> Contam overlap fix

exoctk/exoctk_app/templates/atmospheric_retrievals.html
This PR updates the link to the atmospheric retrieval demo notebook
=> Update pointer to atmospheric retrieval notebook

exoctk/__init__.py, exoctk/utils.py
=> Update version number in utils.py

exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/form_validation.py, exoctk/exoctk_app/templates/limb_darkening.html
This should fix the LDC tool. I think it was just a type error (int should have been float) in the form validation for the LDC.
=> Fixed (I think) the LDC tool so it works on the production server.

exoctk/limb_darkening/limb_darkening_fit.py
Solves issues described in #330
=> Get LDC working (with passing tests) on test server

exoctk/exoctk_app/templates/atmospheric_retrievals.html, setup.py
Merging this PR will update the `exoctk` version number and officially signify our 1.0 release!
=> 1.0 Release

exoctk/exoctk_app/templates/base.html
This PR adds an option to navigate to the Phase Constraint Calculator from the navbar in the web app.
Closes #343
=> Add navbar option for Phase Constraint Calculator

exoctk/notebooks/limb_darkening_demo.ipynb
=> Add note about install instructions to limb darkening demo notebook

README.rst, exoctk/utils.py
This PR adds a `download_exoctk_data` function that downloads exoctk data materials from box, uncompresses them, and organizes them into an `exoctk_data` directory.
=> Add function to utils download exoctk data package

env/environment-3.5.yml, env/environment-3.6.yml, env/environment-3.7.yml, setup.py
see issue linked to this PR
Werkzeug flask 
Closes #358
=> forcing python to install werkzeug==0.16.1

exoctk/exoctk_app/app_exoctk.py, exoctk/lightcurve_fitting/simulations.py, exoctk/limb_darkening/limb_darkening_fit.py, exoctk/modelgrid.py, exoctk/notebooks/lightcurve_fitting_demo.ipynb, exoctk/notebooks/limb_darkening_demo.ipynb, exoctk/tests/test_lightcurve_fitting.py, pip_requirements.txt
Fixes #374 and adds a `save` method to the `limb_darkening.limb_darkening_fit.LDC` class.
Also adds `ACES` and `ATLAS9` child classes to `model grid.py` since those model grids are included in the `EXOCTK_DATA` package. This lets the `LDC` class easily load a model grid without the user having to import the `modelgrid.py` module and instantiating their own `ModelGrid` object to calculate LDCs.
=> Ldc cleanup

exoctk/exoctk_app/app_exoctk.py, exoctk/limb_darkening/limb_darkening_fit.py
Fixes #372 so that the table of LDC results is not truncated.
=> Fixed table truncation in limb darkening results in Web app

exoctk/limb_darkening/limb_darkening_fit.py, exoctk/modelgrid.py
Fixes Issue #382 by checking that the provided model grid path matches the path stored in the pickle and reindexes them if necessary. Also adds the model grid path to the table of results in the LDC class so users can see which models were used in the calculations.
=> Pickle problems

exoctk/notebooks/groups_integrations_demo.ipynb
This PR makes a few minor changes to the Groups and Integrations notebook, mostly to make the installation instructions more clear, and to use more explicit variable names.
=> Some minor updates to the notebook

exoctk/exoctk_app/templates/base.html, exoctk/exoctk_app/templates/limb_darkening.html, exoctk/modelgrid.py, pip_requirements.txt
Moved mu_min div in LDC form and downgraded werkzeug to work with scipy v1.5.2.
Fixes #407
=> [WIP]: Small Web app improvements

env/environment-3.6.yml, env/environment-3.7.yml, exoctk/exoctk_app/app_exoctk.py, pip_requirements.txt
This fixes the issue where the downloaded table of LD coefficients is truncated.
=> Ldc table fix

exoctk/contam_visibility/field_simulator.py
=> original coordinate restriction was too tight

exoctk/contam_visibility/visibilityPA.py, exoctk/exoctk_app/templates/base.html, setup.py
aka , targets that will return an empty badPAs array.
=> [contam visibility] : accounting for cases with 100 percent visibility

exoctk/contam_visibility/field_simulator.py
The binComp parameters get passed as 1 giant string, it seems. So we just needed to turn it into a list of floats.
=> [contam visibility] make binComp a list of floats

exoctk/__init__.py, exoctk/exoctk_app/__init__.py, exoctk/exoctk_app/app_exoctk.py, exoctk/log_exoctk.py
This PR enables logging of all Web tool form submissions in an SQL database.
=> Form logging

CHANGELOG.rst
Hi everyone,
This PR takes on issue #432 of creating a "release notes" document. So far, this only contains the already "done" items for v.1.2, but will update once we have updates on the other items. I'm assigning @hover2pi and @bourque as reviewers for this, as the technical leads.
Thanks!
Néstor
=> Creation of Changelog file

exoctk/__init__.py, exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/form_validation.py, exoctk/helpers.py, exoctk/log_exoctk.py
This PR adds/updates docstrings to adhere to the Tier 2 software standards for INS JWST community tools.  Closes #446.
=> Docstring sweep for tier 2 standards

.github/workflows/ci.yml, env/environment-3.7.yml, env/environment-3.8.yml, env/environment-3.9.yml, pip_requirements.txt, setup.py
This is the same as #498 but for the `develop` branch instead of `master`
=> Add twine dependency [for develop]

exoctk/forward_models/forward_models.py, exoctk/tests/test_forward_models.py
A simple import error was breaking the forward models. This fixes it.
=> Forward model bug fix and unit tests

CHANGELOG.md
=> Changelog for `v1.2.1` release

env/environment-3.8.yml, env/environment-3.9.yml, exoctk/contam_visibility/visibilityPA.py, exoctk/limb_darkening/spam.py, exoctk/modelgrid.py
Upgraded `h5py` and `numpy` and fixed indexing bug in `ModelGrid` that popped up after upgrade.
=> Fixed indexing bug in ModelGrid and bumped h5py and numpy

exoctk/exoctk_app/app_exoctk.py
Small bug is fixed which had the 'visibility only' button throwing an error in the contam tool.
=> Fixed pa_val bug in contam tool

exoctk/exoctk_app/app_exoctk.py, exoctk/exoctk_app/templates/contam_visibility.html
Just updating tool description.
=> Removed MIRI text from contam tool page

exoctk/contam_visibility/contamination_figure.py, exoctk/utils.py, setup.py
- Adds exoctk_data versioning in downloads
- Fixes broken Groups and Integrations download
- Fixes SOSS wavelength path in Contam Tool
=> Fixing downloads and a few other bugs

docker/.env, docker/compose.yaml, docker/dockerfiles/DataDockerfileExoctk, docker/dockerfiles/DataDockerfilePandeia, docker/dockerfiles/DataDockerfileSynphot, docker/exoctk/Dockerfile, docker/pandexo/Dockerfile, docker/redis.yaml, exoctk/tests/test_utils.py
Add a docker directory containing compose.yaml along with yaml files for redis and celery (celery as yet unused). In addition, add dockerfiles for exoctk and pandexo.
=> Add Docker 
